// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . 2 2 2 . . . . 2 2 2 . . . 
. . . 2 2 2 . . . . 2 2 2 . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage1":return img`
........................
........................
........................
........................
..........ffff..........
........ff5555ff........
.......fb555555bf.......
.......f55555555f.......
......f4555555554f......
......f4555555554f......
......f4445555444f......
......fb4bf44fb4bf......
......fc4cf55fc4cf......
.......fb555555bf.......
......fffc4b5b4ffff.....
....fc555cbfbfc555cf....
....f5b5b5ffff5b5b5f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image4":
            case "myImage2":return img`
........................
........................
........................
........................
..........ffff..........
........ff7777ff........
.......fb777777bf.......
.......f77777777f.......
......f6777777776f......
......f6777777776f......
......f6667777666f......
......fb6bf66fb6bf......
......fc6cf77fc6cf......
.......fb777777bf.......
......fffc6b7b6ffff.....
....fc777cbfbfc777cf....
....f7b7b7ffff7b7b7f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image5":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . 2 2 2 2 . . . . 2 2 2 2 . . 
. 2 2 2 2 2 2 . . 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
. 2 2 2 2 2 2 2 2 2 2 2 2 2 2 . 
. . 2 2 2 2 2 2 2 2 2 2 2 2 . . 
. . . 2 2 2 2 2 2 2 2 2 2 . . . 
. . . . 2 2 2 2 2 2 2 2 . . . . 
. . . . . 2 2 2 2 2 2 . . . . . 
. . . . . . 2 2 2 2 . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "myImage0":return img`
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffff9999ffffffffff
ffffffffb999999bffffffff
ffffffff99999999ffffffff
fffffff8999999998fffffff
fffffff8999999998fffffff
fffffff8889999888fffffff
fffffffb8bf88fb8bfffffff
fffffffc8cf99fc8cfffffff
ffffffffb999999bffffffff
fffffffffc8b9b8fffffffff
fffffc999cbfbfc999cfffff
fffff9b9b9ffff9b9b9fffff
fffffbfbffffffbfbfbfffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
ffffffffffffffffffffffff
`;
            case "image6":
            case "myImage4":return img`
........................
........................
........................
........................
..........ffff..........
........ff9999ff........
.......fb999999bf.......
.......f99999999f.......
......f8999999998f......
......f8999999998f......
......f8889999888f......
......fb8bf88fb8bf......
......fc8cf99fc8cf......
.......fb999999bf.......
......fffc8b9b8ffff.....
....fc999cbfbfc999cf....
....f9b9b9ffff9b9b9f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image7":
            case "myImage5":return img`
. . . . f f f f . . . . . 
. . f f f f f f f f . . . 
. f f f f f f c f f f . . 
f f f f f f c c f f f c . 
f f f c f f f f f f f c . 
c c c f f f 4 4 f f c c . 
f f f f f 4 4 f f c c f . 
f f f b f 4 4 f b f f f . 
. f 4 1 f 4 4 f 1 4 f . . 
. f e e e e e e e e f . . 
. f f e e e e e e f f . . 
f 4 f 2 2 2 2 2 2 f 4 f . 
4 4 f 2 2 2 2 2 2 f 4 4 . 
4 4 f e e 5 5 e e f 4 4 . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`;
            case "image8":
            case "myImage6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . c c c c c c c c c . . . 
. . . . c c c f f f c c c . . . 
. . . . c c c f f f c c c . . . 
. . . . c c c f f f c c c . . . 
. . . . c c c c f c c c c . . . 
. . . . c c c c f c c c c . . . 
. . . . c c c c f c c c c . . . 
. . . . c c c c f c c c c . . . 
. . . . c c c c c c c c c . . . 
. . . . c c c c c c c c c . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "myImage7":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 5 5 5 . . . . . . . 
. . . . . 5 5 f 5 5 . . . . . . 
. . . . . 5 5 f 5 5 . . . . . . 
. . . . . . 5 5 5 . . . . . . . 
. . . . . . . 5 . . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . 5 . . . . . . . . 
. . . . . . . 5 5 . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
